spring:
  datasource:
      url: jdbc:mysql://rm-bp1rc23s40ss8j9lw.mysql.rds.aliyuncs.com:3306/05apolloconfigdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: user_05
      password: S9BlaFG9HIfmUkdT

