spring:
  datasource:
      url: jdbc:mysql://rm-bp1rc23s40ss8j9lw.mysql.rds.aliyuncs.com:3306/02apolloportaldb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: user_02
      password: 3pILfWsofG0e2ebP

